title: Gitbash-NPZ
description: Tasks studies - laboratory
GitHub Stars: https://github.com/dawidolko/Gitbash-NPZ
icon: logo.png
favicon: "logo.png"
show_downloads: true
theme: jekyll-theme-midnight
# github:
#   zip_url: https://gb.dawidolko.pl/download.zip
#   another_url: another value
